name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - stage

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    environment: Deploy

    steps:
      - name: Build and Deploy to Vercel
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information - Preview
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        id: deploy
        run: |
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "url=$DEPLOYMENT_URL" >> "$GITHUB_OUTPUT"

      - name: Alias Preview Deployment to Staging Domain
        run: vercel alias set ${{ steps.deploy.outputs.url }} stage.acfsports.com.br --token=${{ secrets.VERCEL_TOKEN }}
